from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from reven.jobs.repository import JobClaim
from reven.publishing.blog.workspace import TrustedArtifact
from reven.publishing.commands import CommandResult


class GitHubApi(Protocol):
    async def default_branch(self) -> str: ...
    async def branch(self, name: str) -> dict[str, Any] | None: ...
    async def pull_requests(self, head: str, *, base: str, state: str = "all") -> list[dict[str, Any]]: ...
    async def pull_request_template(self, default_branch: str) -> str | None: ...
    async def create_pull_request(self, *, title: str, head: str, base: str, body: str) -> dict[str, Any]: ...
    async def get_pull(self, number: int) -> dict[str, Any]: ...
    async def required_contexts(self, branch: str) -> tuple["RequiredCheck", ...]: ...
    async def check_runs(self, sha: str) -> list[dict[str, Any]]: ...
    async def status_contexts(self, sha: str) -> list[dict[str, Any]]: ...
    async def merge(self, number: int, sha: str) -> dict[str, Any]: ...
    async def pages_builds(self) -> list[dict[str, Any]]: ...
    async def verify_article(self, path: str, title: str) -> str: ...


class ResultStore(Protocol):
    async def load(self, claim: JobClaim) -> dict[str, object]: ...
    async def assert_lease(self, claim: JobClaim) -> bool: ...
    async def save_result(self, claim: JobClaim, patch: dict[str, object]) -> bool: ...
    async def clear_operation(self, claim: JobClaim, operation_id: str) -> bool: ...
    async def begin_operation_if_absent(self, claim: JobClaim, phase: str) -> str | None: ...


class BlogWorkspacePort(Protocol):
    def create_attempt(self, job_id: str) -> Path: ...
    async def clone_at(self, path: Path, remote_url: str, token: str) -> Path: ...
    async def prepare(self, path: Path, branch: str) -> None: ...
    async def switch(self, path: Path, branch: str) -> None: ...
    async def build(self, path: Path) -> None: ...
    def capture_artifacts(self, root: Path, manifest: tuple[Path, ...]) -> tuple[TrustedArtifact, ...]: ...
    def verify_artifacts(self, root: Path, trusted: tuple[TrustedArtifact, ...]) -> None: ...
    def restore_artifacts(self, root: Path, trusted: tuple[TrustedArtifact, ...]) -> None: ...
    def cleanup_repository(self, path: Path) -> None: ...
    async def commit(self, path: Path, manifest: tuple[Path, ...], title: str) -> str: ...
    async def push(self, path: Path, remote_url: str, branch: str, token: str) -> CommandResult: ...
    def cleanup_attempt(self, attempt: Path) -> None: ...


@dataclass(frozen=True)
class BlogPublishResult:
    article_url: str
    pull_request_number: int
    merge_sha: str


@dataclass(frozen=True)
class RequiredCheck:
    context: str
    app_id: int | None = None


Sleep = Callable[[float], Awaitable[None]]
